image: node:14

cache:
  paths:
    - node_modules/

install:
  script:
    - npm i

lint:
  script:
    - npm run lint
    - npm run stylelint
    - npm run typecheck

test:
  script:
    - npm run test:ci

build:
  script:
    - npm run build
