image: node:14
stages:
  - install
  - test
  - build

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm i

test:
  needs: [install]
  stage: test
  script:
    - npm run lint
    - npm run stylelint
    - npm run test:ci

build:
  needs: [test]
  stage: build
  script:
    - npm run build
