image: node:14
stages:
    - install
    - lint
    - test
    - build

cache:
    paths:
        - node_modules/

install:
    stage: install
    script:
        - npm i

lint:
    needs: [install]
    stage: lint
    script:
        - npm run lint
        - npm run stylelint

test:
    needs: [lint]
    stage: test
    script:
        - npm run test:ci

build:
    needs: [test]
    stage: build
    script:
        - npm run build
